### ISSUE TITLE
File associations for Windows platform do not work, the issue is only resolved via "bat" scripts

### ISSUE THREAD

**Issue by pgagarinov** [simgunz/doxymatlab#2]

**Comment by tomatt** [comment]
I just had the same problem. 
I solved it in another way:
1. The command line arguments are 2 commands which is not clear due to the missing line break:
assoc .pl=PerlScript 
ftype PerlScript="C:\Program Files\MATLAB\R2010b\sys\perl\win32\bin\perl.exe" "%1" %*
2. Add the "" to the path above
3. There may be some errors in the registry. Open regedit.exe, search for perl.exe and append the "%*" to all calls found. 
Then it also worked for me!

**Comment by simgunz** [comment]
If I understand correctly the solution provided  by @pgagarinov  solves the problem without the need to touch regedit, which seems better. I'll soon test the proposed changes and I'll integrate them.
